"use strict";
var chcompo = chcompo || {};

chcompo={
		member :()=>{
			return '<div class="wrapper">'
		    +'<div class="sidebar">'
	    	+'<div class="sidebar-wrapper">'
	            +'<div class="logo">'
	                +'<a href="#" class="simple-text">'
	                    +'낚어 관리자'
	                +'</a>'
	            +'</div>'
	            +'<ul class="nav">'
	                +'<li class="active">'
	                    +'<a href="#">'
	                        +'<i class="member"></i>'
	                        +'<img src="/web/resources/img/admin/member.png"'
	                        +'<p>회원관리</p>'
	                    +'</a>'
	                +'</li>'
	                +'<li>'
	                    +'<a id="resnav"href="#">'
	                        +'<i class="reservation"></i>'
	                        +'<img src="/web/resources/img/admin/reservation.png"'
	                        +'<p>예약관리</p>'
	                    +'</a>'
	                +'</li>'
	                +'<li>'
	                    +'<a href="#">'
	                        +'<i class="quote"></i>'
	                        +'<img src="/web/resources/img/admin/fish.png"'
	                        +'<p>시세&조과</p>'
	                    +'</a>'
	                +'</li>'
	                +'<li>'
	                    +'<a href="#">'
	                        +'<i class="lank"></i>'
	                        +'<img src="/web/resources/img/admin/lank.png"'
	                        +'<p>랭킹</p>'
	                    +'</a>'
	                +'</li>'
/*	                +'<li>'
	                    +'<a href="#">'
	                        +'<i class="aa"></i>'
	                        +'<p>Icons</p>'
	                    +'</a>'
	                +'</li>'
	                +'<li>'
	                    +'<a href="#">'
	                        +'<i class="bb"></i>'
	                        +'<p>Maps</p>'
	                    +'</a>'
	                +'</li>'*/
	            +'</ul>'
	    	+'</div>'
	    +'</div>'
	    +'<div class="main-panel" style="padding-right: 80px;padding-left: 80px ;height: 650px;">'
	        +'<div class="content" style="padding-top: 0px;">'
	            +'<div class="container-fluid">'
	                +'<div class="row" style="margin-bottom: 50px;">'
	                    +'<div class="col-md-4">'
	                        +'<div class="card" style="height: 120px;">'
	                            +'<div class="header">'
	                                +'<h4 class="title">총 회원수</h4>'
	                            +'</div>'
	                            +'<div class="content contentcount counter" id="total"style="height: 70px;">'
	                            +'</div>'
	                        +'</div>'
	                    +'</div>'
	                    +'<div class="col-md-4">'
                        +'<div class="card" style="height: 120px;">'
                            +'<div class="header">'
                                +'<h4 class="title">오늘 방문자수</h4>'
                            +'</div>'
                            +'<div class="content contentcount counter" id="today" style="height: 70px;">'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<div class="col-md-4">'
                    +'<div class="card" style="height: 120px;">'
                        +'<div class="header">'
                            +'<h4 class="title">어제 방문자수</h4>'
                        +'</div>'
                        +'<div class="content contentcount counter" id="yesterday"style="height: 70px;">'                           
                        +'</div>'
                    +'</div>'
                +'</div>'                    
	                +'</div>'
	                +'<div class="row" style="padding-bottom: 50px;">'
	                    +'<div class="col-md-12" >'
	                        +'<div class="card ">'
	                            +'<div class="chart-container" >'
	                            +'<canvas id="myChart"style="position: relative; height:40vh; width:80vw"></canvas>'
	                            +'</div>'
	                           /* +'<div id="chart_div" style="padding:0px 0px 0px 0px;"></div>'*/
	                           /* +'<div id="controlsArea" style="padding:0px 0px 0px 0px;"></div>'*/
	                            +'</div>'
	                        +'</div>'
	                    +'</div>'
		                +'<div class="row">'
	                    +'<div class="col-md-12" >'
	                        +'<div class="card ">'
	                            +'<div class="chart-container" >'
	                            +'<canvas id="age"style="position: relative; height:45vh; width:80vw"></canvas>'
	                            +'</div>'
	                           /* +'<div id="chart_div" style="padding:0px 0px 0px 0px;"></div>'*/
	                           /* +'<div id="controlsArea" style="padding:0px 0px 0px 0px;"></div>'*/
	                            +'</div>'
	                        +'</div>'
	                    +'</div>'
	                +'</div>'
	            +'</div>'
	        +'</div>'
	    +'</div>'
	+'</div>'
	},
	admin:()=>{
		return '<div class="col-md-12">'
		+'	<div class="card col-md-12">'
		
	    +'         <div class="col-md-4"style="padding-right: 0px;padding-left: 0px;width: 180px;">'
        +'            <input class="respicker" type="text" id="datepicker" style="width: 112px;text-align: center;">'
        +'<span id="clai" class="glyphicon glyphicon-calendar glyphicon-align-right" aria-hidden="true"></span>'
        +'         </div>'
        
        +'<div class="dropdown col-md-4" style="padding-left: 0px;padding-right: 0px;width: 150px;">'
        +'  <button class="btn btn-default dropdown-toggle searchdrop" type="button" id="dropdownMenu1"'
        +'data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">'
        +'    출발/예약'
        +'    <span class="caret"></span>'
        +'  </button>'
        +'  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
        +'    <li><a href="#">출발날짜</a></li>'
        +'    <li><a href="#">예약날짜</a></li>'
        +'  </ul>'
        +'</div>'
        
        +'<div class="dropdown col-md-4" style="padding-left: 0px;padding-right: 0px;width: 150px;">'
        +'  <button class="btn btn-default dropdown-toggle searchdrop" type="button" id="dropdownMenu2"'
        +'data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">'
        +'    상품종류'
        +'    <span class="caret"></span>'
        +'  </button>'
        +'  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">'
        +'    <li><a href="#">바다낚시</a></li>'
        +'    <li><a href="#">민물낚시</a></li>'
        +'  </ul>'
        +'</div>'
        
		+'<table class="table table-responsive"id="restable">'
		+'</table>'
		+'<nav id="adresnav" aria-label="Page navigation example">'
		+'</nav>'
		+'	</div>'
		+'</div>'
	}	
}