"use strict";
var eycompo = eycompo || {};
eycompo ={
		commonnav :()=>{
			return '<nav class="navbar navbar-inverse navbar-default" role="navigation" id="comnav" data-spy="affix" data-offset-top="525" style="width: 100%; height:50px; background-color: #fafafa; border: none; border-bottom: 1px solid; border-color: #ddd; border-radius: 0px; margin-bottom:0px;">	  '
			+'<div class="container-fluid">'
			+'<ul class="nav navbar-nav">'
			+'      <li id="home"><a href="#">HOME</a></li>'
			+'      <li id="ocean"><a href="#">OCEAN</a></li>'
			+'      <li id="river"><a href="#">RIVER</a></li>'
			+'      <li id="hotel"><a href="#">HOTEL</a></li>'
			+'      <li id="aquagram"><a href="#">AQUAGRAM</a></li>'
			+'      <li id="mypage"><a href="#">MYPAGE</a></li>'
			+'      <li id="logout"><a href="#">LOGOUT</a></li>'
			+'</ul>'
			+'</div>'
			+'</nav>'
		},

		search_bar : ()=>{
			return '<section class="newsletter">'
			+'      <div class="container">'
			+'        <div class="row">'
			+'          <div class="col-md-10 col-sm-10 col-md-offset-1 col-sm-offset-1">'
			+'          <div class="input-group">'
			+'            <input id="search_keyword" type="text" class="form-control" placeholder=" 낚시하러갈 땐 낚어 ">'
			+'            <span class="input-group-btn">'
			+'              <button type="button" class="btn btn-default">SEARCH</button>'
			+'            </span>'
			+'          </div>'
			+'          </div>'
			+'        </div>'
			+'      </div>'
			+'    </section>'
		},
		
		main_search:()=>{
			return '<!-- 검색창 -->'
		    +'<div>'
		    +'<section id="search_content" class="main-banner">'
		      +'<div class="container">'
		        +'<div class="caption">'
		          +'<h2>PLAN YOUR NEXT FISHING</h2>'
		          +'<form>'
		            +'<fieldset>'
		              +'<div class="col-md-4 col-sm-4 no-pad">'
		              +'<input id="search_keyword" type="text" class="form-control border-right" placeholder="검색어" />'
		              +'</div>'
		              +'<div id="load-target" class="col-md-3 col-sm-3 no-pad">'
		             /* +'<input type="text" class="form-control border-right hasDatepicker" id="date_search">'*/
		              +'</div>'
		              +'<div class="col-md-3 col-sm-3 no-pad">'
		                +'<select class="selectpicker">'
		                  +'<option>인원 선택</option>'
		                  +'<option>1</option>'
		                  +'<option>2</option>'
		                  +'<option>3</option>'
		                  +'<option>4 + </option>'
		                +'</select>'
		              +'</div>'
		              +'<div class="col-md-2 col-sm-2 no-pad">'
		                +'<input type="submit" class="btn seub-btn" value="SEARCH" />'
		              +'</div>'
		            +'</fieldset>'
		          +'</form>'
		        +'</div>'
		      +'</div>'
		    +'</section>'
		    +'</div>'
		    +'<!-- 검색창  끝-->'
		    +''
		    +'<!-- 메인 화면  -->'
		    +'<div class="features" id="feat" style="padding-top: 20px;">'
		    +'<div id="main-container" class="container-fluid">'
		    +'</div>'
		    +'</div></br></br>'
		},
		
		item_container : ()=>{
			return '<div class="col-md-12">'
			+'					<div class="row">'
			+'						<div class="basic-information">'
			+'<div class="col-md-12 view_area container"id="info_content">'
		    +'<!-- 예약정보 -->'
		    +'<div id="view_reserve" class="view_info view_info_reserve view_contents"style="padding-bottom: 0px;">'
		        +'<section class="full_section" id="calendar_tab" style="padding-bottom: 0px;">'
		            +'<div class="calendar_area view_box">'
		                +'<div class="calendar_wrap">'
		                    +'<div class="calendar_title clearfix">'
		                        +'<p class="title_arrow">'
		                            +'2019년 05월 <a class="calendar_next"><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/basic/calendar_next.png" alt=""></a>'
		                        +'</p>'
		                        +'<!-- <span class="one_ticket">천원한장</span> -->'
		                    +'</div>'
		                    +'<!--// calendar_title -->'
		                    +'<div class="calendar_201905">'
		                        +'<table class="calendar">'
		                            +'<tbody>'
		                                +'<tr>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td>일</td>'
		                                    +'<td>월</td>'
		                                    +'<td>화</td>'
		                                    +'<td>수</td>'
		                                    +'<td>목</td>'
		                                    +'<td>금</td>'
		                                    +'<td>토</td>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td style="color: #666;"><a class="off"><strong>28</strong></a></td>'
		                                    +'<td style="color: #666;"><a class="off"><strong>29</strong></a></td>'
		                                    +'<td style="color: #666;"><a class="off"><strong>30</strong></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-01"><strong>1</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-30.png" alt=""><span>3물</span></a></td>'
		                                    +'<td><a class="cal_cell_date on" data-date="2019-05-02"><strong>2</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>4물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-03"><strong>3</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>5물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-04"><strong>4</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>6물</span></a></td>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td><a class="cal_cell_date sunday" data-date="2019-05-05"><strong>5</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-30.png" alt=""><span>7물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-06"><strong>6</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-30.png" alt=""><span>8물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-07"><strong>7</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>9물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-08"><strong>8</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>10물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-09"><strong>9</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-30.png" alt=""><span>11물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-10"><strong>10</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>12물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-11"><strong>11</strong><img src="https://img.moolban.com/unsafe/asset/www/responsive/img/weather/weather-10.png" alt=""><span>13물</span></a></td>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td><a class="cal_cell_date sunday" data-date="2019-05-12"><strong>12</strong><span>조금</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-13"><strong>13</strong><span>무시</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-14"><strong>14</strong><span>1물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-15"><strong>15</strong><span>2물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-16"><strong>16</strong><span>3물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-17"><strong>17</strong><span>4물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-18"><strong>18</strong><span>5물</span></a></td>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td><a class="cal_cell_date sunday" data-date="2019-05-19"><strong>19</strong><span>6물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-20"><strong>20</strong><span>7물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-21"><strong>21</strong><span>8물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-22"><strong>22</strong><span>9물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-23"><strong>23</strong><span>10물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-24"><strong>24</strong><span>11물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-25"><strong>25</strong><span>12물</span></a></td>'
		                                +'</tr>'
		                                +'<tr>'
		                                    +'<td><a class="cal_cell_date sunday" data-date="2019-05-26"><strong>26</strong><span>13물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-27"><strong>27</strong><span>조금</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-28"><strong>28</strong><span>무시</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-29"><strong>29</strong><span>1물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-30"><strong>30</strong><span>2물</span></a></td>'
		                                    +'<td><a class="cal_cell_date" data-date="2019-05-31"><strong>31</strong><span>3물</span></a></td>'
		                                    +'<td style="color: #666;"><a class="off"><strong>1</strong></a></td>'
		                                +'</tr>'
		                            +'</tbody>'
		                        +'</table>'
		                    +'</div>'
		                +'</div>'
		            +'</div>'
		        +'</section>'		   
		        +'<section id="reserve_section" style="padding-top:0px;padding-bottom: 10px;">'
		            +'<a class="reserve_area  view_box" data-cg-key="10342" data-gi-type="1" data-gi-key="1483447">'
		                +'<div class="reserve_con">'
		                    +'<span class="count_pic">남은수8명</span>'
		                    +'<p id="proname" class="reserve_title"></p>'
		                    +'<div class="reserve_price">'
		                        +'<p id="price" class="reserve_pay"><span>  원</span></p>'
		                    +'</div>'
		                    +'<div class="reserve_dot">'
		                        +'<p> 최소인원 : 5명 </p>' 
		                        +'<p> 최대인원 : 20명 </p>'
		                        +'어종 : <p id="fishname"></p>'
		                    +'</div>'
		                +'</div>'
		            +'</a>'
		        +'</section>'
		        +'<section class="full_section" style=padding-top:0px;padding-bottom:0px;>'

		            +'<div class="view_box info_view_sty8" style="margin-bottom: 0px;">'
		                +'<p class="view_box_title">편의시설</p>'
		                +'<ol class="in_box clearfix">'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/air_conditioner.png" alt="">에어컨</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/tv.png" alt="">tv</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/toilet.png" alt="">화장실</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/life_jacket.png" alt="">구명조끼</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/life_belt.png" alt="">구명밧줄</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/karaoke.png" alt="">노래방</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/heating.png" alt="">난방</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/fridge.png" alt="">냉장고</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/fire_exting.png" alt="">소화기</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/fan.png" alt="">선풍기</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/cctv.png" alt="">CCTV</li>'
		                    +'<li><img src="https://img.moolban.com/unsafe/images/web_ver/siseol/view/canopy.png" alt="">그늘막</li>'
		                +'</ol>'
		    			+'<!-- fixed bottom read_only-->'
		    			+'<div class="view_fixed 11">'
		    			+'    <section style="padding-bottom: 0px;">'
		    			+'    	<a id="select_item" class="sel_reserve_goods" data-type="1" data-saledate="2019-05-02">상품선택</a>'
		    			+'    </section>'
		    			+'</div>'

		                +'</div>'
		        +'</section>'
		        +'<!-- fixed bottom read_only-->'
		        +'<!--// fixed bottom -->'
		    +'</div>'
		    +'<div id="map" class="container-fluid" style="height: 500px;"></div>'
		    +'<!--// view_contents -->'
		    +'<!--// 예약정보 -->'
		+'</div>'
			+'						</div>'
			+'					</div>'
			+'				</div>'
			+'							</br>'
		},
		
		product_info:()=>{
			return '<section class="proslide">'
			    +'<div class="view_profile clearfix">'
		        +'<div class="profile_slide swiper-container swiper-container-horizontal">'
		        +'<img id="proimg" alt="" style="width: 600px;">'
	            +'</div>'
		        +'<!-- 업체 정보 -->'
		        +'<div class="profile_info">'
		            +'<dl class="clearfix">'
		                +'<dt>'
		                    +'<span class="ico_pic ico_pic1">종일</span>'
	                        +'<em>보험</em>'
	                        +'<strong id="company"></strong>'
		                +'</dt>'
		                +'<dd id="proaddress"></dd>'
		                +'<dd class="call_dd"><a class="login_tel" data-key="1318"></a></dd>'
		            +'</dl>'
		            +'<div class="like_call_link">'
		                +'<a class="like_link" href="/mypage/login?redirect=%2Fcompany%2F1318"></a>'
		                +'<a class="call_link mblock login_tel" data-key="1318"></a>'
		            +'</div>'
		        +'</div>'
		        +'<!--// 업체 정보 -->'
			    +'</div>'
			    +'<!--// view_profile -->'
				+'</section>'
		},
	
		product_pay:()=>{
			return '<div id="app">'
			+'    <section style="">'
			+'        <section>'
			+'            <dl class="reserve_title clearfix"><dt>결제수단</dt>'
			                +'<dd><span><span class="">상품정보</span> <span> &gt; </span></span><span><span class="on">결제수단</span> <span style="display: none;"> &gt; </span></span>'
			+'                </dd>'
			+'            </dl>'
			+'        </section>'
			+'        <div class="clearfix">'
			+'            <div class="content_left" style="float: left;">'
			+'                <div class="auth_area reserve_area">'
			+'                    <div class="box_title clearfix">'
			+'                        <p class="ico_auth">예약자 정보</p>'
			+'                    </div>'
			+'                    <div class="inner clearfix">'
			+'                        <div class="auth_box">'
			+'                            <p>예약자명</p> <input type="text" placeholder="예약자명을 입력해주세요."></div>'
			+'                        <div class="auth_box input_btn">'
			                            +'<p>휴대폰번호</p> <input type="tel" placeholder="휴대폰번호를 입력해주세요." maxlength="11"> <a class="resend" style="display: none;">재전송</a> <a class="active">인증하기</a> <a style="display: none;">변경</a></div>'
			+'                        <div class="auth_box auth_chk" style="display: none;">'
			+'                            <p>인증번호</p> <input type="text" maxlength="4" value="" placeholder="0000"> <a class="active">확인</a>'
			+'                            <p class="time_txt">남은 시간 : 300초</p>'
			+'                        </div>'
			+'                    </div>'
			+'                </div>'
			+'                <div>'
			+'                    <div class="reserve_area secInner result_area">'
			+'                        <div class="box_title clearfix">'
			+'                            <p class="ico_goods">광어/우럭(오후)</p>'
			+'                        </div>'
			+'                        <div class="inner reserve_tb">'
			+'                            <div class="reserve_td_tit clearfix">'
			+'                                <p class="tb1">상품정보</p>'
			+'                                <p class="tb2">수량</p>'
			+'                                <p class="tb3">금액</p>'
			+'                            </div>'
			+'                            <div class="reserve_td_con">'
			+'                                <div class="clearfix">'
			+'                                    <p class="tb1">광어/우럭(오후)</p>'
			+'                                    <p class="tb2">1명</p>'
			+'                                    <p class="tb3">40,000원</p>'
			+'                                </div>'
			+'                            </div>'
			+'                        </div>'
			+'                        <div class="result_price">'
			+'                            <div class="price_box clearfix">'
			+'                                <dl><dt>상품 금액</dt>'
			+'                                    <dd>40,000원</dd>'
			+'                                </dl> <i>-</i>'
			+'                                <dl><dt class="mulban_txt">할인 금액</dt>'
			+'                                    <dd class="mulban_txt"><strong><span class="mulban_txt" style="display: inline;">0원</span></strong></dd>'
			+'                                </dl> <i>=</i>'
			+'                                <dl><dt>쿠폰 적용 금액</dt>'
			+'                                    <dd><strong><span style="display: inline;">40,000원</span></strong></dd>'
			+'                                </dl>'
			+'                            </div>'
			+'                        </div>'
			+'                        <!---->'
			+'                        <!---->'
			+'                    </div>'
			+'                </div>'
			+'            </div>'
			+'            <div class="content_right">'
			+'                <div>'
			+'                    <div class="order_area reserve_area">'
			+'                        <div class="box_title clearfix">'
			+'                            <p class="ico_goods">주문 목록</p>'
			+'                        </div>'
			+'                        <div class="inner">'
			+'                            <p><span>상품</span>광어/우럭(오후)'
			+'                            </p>'
			+'                        </div>'
			+'                    </div>'
			+'                    <div class="price_area reserve_area">'
			+'                        <div class="box_title clearfix">'
			+'                            <p class="ico_price">최종 결제 금액</p>'
			+'                        </div>'
			+'                        <div class="inner">'
			+'                            <p>총 상품금액<span>40,000원</span></p>'
			+'                            <p style="display: none;">상품 할인<span><span style="display: inline;">- 0원</span></span>'
			+'                            </p>'
			+'                            <p style="display: none;">장바구니 할인<span><span style="display: inline;">- 0원</span></span>'
			+'                            </p>'
			+'                            <p style="display: none;">보험 금액<span>0원</span></p>'
			+'                        </div>'
			+'                        <div class="price_box">'
			+'                            <dl class="clearfix"><dt>결제금액</dt>'
			+'                                <dd><span style="display: inline;">40,000</span><span>원</span></dd>'
			+'                            </dl>'
			+'                        </div>'
			+'                    </div>'
			+'                    <div class="pay_area reserve_area">'
			+'                        <div class="box_title clearfix">'
			+'                            <p class="ico_pay">결제수단</p>'
			+'                        </div>'
			+'                        <div class="inner">'
			                            +'<div class="pay_chk_box pay_choice2"><a class="pay_card_btn on"><span class="pay_chk">신용카드</span> <div class="choice_box" style="display: none;"></div></a><a class="pay_phone_btn"><span class="pay_chk">휴대폰</span> <div class="choice_box" style="display: none;"></div></a></div>'
			+'                            <div class="pay_zero pay_choice2" style="display: none;">'
			+'                                <p>최종결제금액이 0원이라면?<span>결제수단 확인없이 간.편.하.게 결제가 완료됩니다!</span></p>'
			+'                            </div>'
			+'                        </div>'
			                        +'<div class="pay_agree"><label class="clearfix"><input type="checkbox"> <ins></ins> <span><em>취소규정</em>, <em>개인정보 제3자 제공약관</em>에 동의합니다.</span></label></div>'
			+'                    </div>'
			+'                </div>'
			+'                <div>'
			+'                    <div><a class="reserve_btn gray mulbanf_btn">결제하기</a></div>'
			+'                </div>'
			+'            </div>'
			+'        </div>'
			+'    </section>'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <!---->'
			+'    <div id="paymentExec" style="display: none;"></div>'
			+'    <!---->'
			+'</div>'
		}
		
};