DROP TABLE MEMBERS;
DROP TABLE FISHES;
DROP TABLE MEMBERFISH;
DROP TABLE RESERVATION;
DROP TABLE PRODUCTS;
DROP TABLE FOLLOWERS;
DROP TABLE ARTICLES;
DROP TABLE COMMENTS;
DROP TABLE TAGS;
DROP TABLE POSTTAG;
DROP TABLE VISITOR;
CREATE TABLE MEMBERS
(
mid       VARCHAR(50) PRIMARY KEY,
password  VARCHAR(50)     NOT NULL,
name      VARCHAR(50)     NOT NULL,
birth     VARCHAR(100)    NOT NULL,
mail      VARCHAR(100)    NULL,
phone     VARCHAR(80)     NOT NULL,
profilephoto VARCHAR(100) NULL
);
CREATE TABLE FISHES
(
fishseq   INT AUTO_INCREMENT PRIMARY KEY,
fishname  VARCHAR(100)    NOT NULL,
kind      VARCHAR(100)    NOT NULL,
habitat   VARCHAR(100)    NOT NULL
);
CREATE TABLE MEMBERFISH
(
mfishseq    INT         AUTO_INCREMENT PRIMARY KEY,
len       VARCHAR(50) NULL,
wei       VARCHAR(50) NULL,
date      VARCHAR(50) NULL,
mid       VARCHAR(50) NOT NULL,
fishseq   INT         NOT NULL
);
/*
ALTER TABLE Memberfish
ADD CONSTRAINT FK_Memberfish_mid_Member_mid FOREIGN KEY (mid)
REFERENCES Member (mid) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE Memberfish
ADD CONSTRAINT FK_Memberfish_fishseq_Fish_fishseq FOREIGN KEY (fishseq)
REFERENCES Fish (fishseq) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
CREATE TABLE RESERVATION
(
resnum   INT AUTO_INCREMENT PRIMARY KEY,
mid       VARCHAR(50)    NOT NULL,
resname   VARCHAR(50)    NOT NULL,
startdate VARCHAR(50)    NOT NULL,
ampm      VARCHAR(100)    NOT NULL,
phone     VARCHAR(50)    NOT NULL,
resdate       VARCHAR(50)    NOT NULL,
rescount  VARCHAR(50)    NOT NULL,
deposit   VARCHAR(70)    NOT NULL,
message   VARCHAR(200)   NOT NULL,
proname   VARCHAR(50)    NOT NULL,
pronum   INT            NOT NULL
);
CREATE TABLE PRODUCTS
(
pronum    INT AUTO_INCREMENT PRIMARY KEY,
proname  VARCHAR(100)    NOT NULL,
price     VARCHAR(100)    NOT NULL,
company   VARCHAR(100)    NOT NULL,
address   VARCHAR(100)    NOT NULL,
category  VARCHAR(40)     NOT NULL,
proimg    VARCHAR(45)     NOT NULL,
regidate  VARCHAR(70)     NOT NULL,
fishname  VARCHAR(70)     NULL,
phone  VARCHAR(70)        NULL,
lat  VARCHAR(70)          NULL,
lng  VARCHAR(70)          NULL
);
/*
ALTER TABLE Reservation
ADD CONSTRAINT FK_Reservation_mid_Member_mid FOREIGN KEY (mid)
REFERENCES Member (mid) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
CREATE TABLE FOLLOWERS
(
folloseq  INT AUTO_INCREMENT PRIMARY KEY,
folloid   VARCHAR(45)    NOT NULL,
mid       VARCHAR(50)    NOT NULL
);
/*
ALTER TABLE Follower
ADD CONSTRAINT FK_Follower_mid_Member_mid FOREIGN KEY (mid)
REFERENCES Member (mid) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
CREATE TABLE ARTICLES
(
artnum    INT AUTO_INCREMENT PRIMARY KEY,
content   VARCHAR(300)    NOT NULL,
artdate   VARCHAR(80)     NOT NULL,
artphoto  VARCHAR(45)     NOT NULL,
extension VARCHAR(50)     NOT NULL,
mid       VARCHAR(50)     NOT NULL
);
/*
ALTER TABLE Article
ADD CONSTRAINT FK_Article_mid_Member_mid FOREIGN KEY (mid)
REFERENCES Member (mid) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
CREATE TABLE COMMENTS
(
commseq   INT AUTO_INCREMENT PRIMARY KEY,
titleseq  INT NOT NULL,
comm      VARCHAR(100) NOT NULL,
comid    VARCHAR(50) NOT NULL
);
/*
ALTER TABLE Comment
ADD CONSTRAINT FK_Comment_titleseq_Article_artnum FOREIGN KEY (titleseq)
REFERENCES Article (artnum) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
CREATE TABLE TAGS
(
tagname  VARCHAR(70) NOT NULL PRIMARY KEY
);
CREATE TABLE POSTTAG
(
ptseq    INT AUTO_INCREMENT PRIMARY KEY,
artseq   INT NOT NULL,
tagname  VARCHAR(70) NOT NULL
);
CREATE TABLE VISITOR
(
VISITSEQ   INT AUTO_INCREMENT PRIMARY KEY,
VISITID  VARCHAR(100)    NOT NULL,
VISITTIME      VARCHAR(100)    NOT NULL);
/*
ALTER TABLE Posttag
ADD CONSTRAINT FK_Posttag_artseq_Article_artnum FOREIGN KEY (artseq)
REFERENCES Article (artnum) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE Posttag
ADD CONSTRAINT FK_Posttag_tagname_Tag_tagbane FOREIGN KEY (tagname)
REFERENCES Tag (tagbane) ON DELETE RESTRICT ON UPDATE RESTRICT;
*/
COMMIT;       